src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $pointswin = null;

    /**
     * @var Collection<int, Items>
     */
    #[ORM\OneToMany(targetEntity: Items::class, mappedBy: 'category')]
    private Collection $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPointswin(): ?int
    {
        return $this->pointswin;
    }

    public function setPointswin(int $pointswin): static
    {
        $this->pointswin = $pointswin;

        return $this;
    }

    /**
     * @return Collection<int, Items>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Items $item): static
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setCategory($this);
        }

        return $this;
    }

    public function removeItem(Items $item): static
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getCategory() === $this) {
                $item->setCategory(null);
            }
        }

        return $this;
    }

    public function getItemCount(): int
    {
    return $this->items->count();
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Repository\CategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CategorieController extends AbstractController
{
    #[Route('/categorie', name: 'app_categorie')]
    public function index(CategoriesRepository $categoriesRepository,): Response
    {
        $category = $categoriesRepository->findAll();

        return $this->render('categorie/index.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/categorie/{id}', name: 'app_categorie_id')]
    public function id(CategoriesRepository $categoriesRepository, $id): Response
    {
        $category = $categoriesRepository->find($id);

        return $this->render('categorie/information.html.twig', [
            'category' => $category,
        ]);
    }
}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Toutes les catégories{% endblock %}

{% block body %}
<style>
    .miniMenu {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: -10px;
    }

    a {
        text-decoration:none;
    }
</style>
<div class="miniMenu">
    <p>Accueil - Toutes les catégories</p>
</div>

<ul class="list-group">

{% for category in category %}
<a href="{{ path('app_categorie_id', {id: category.id}) }}">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    {{ category.name }}
    <span class="badge text-bg-primary rounded-pill">{{ category.itemCount }}</span>
  </li>
</a>
  <br>
{% endfor %}
</ul>
{% endblock %}

templates/categorie/information.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category.name }}{% endblock %}

{% block body %}

<style>
    .miniMenu {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: -10px;
        margin-bottom: 20px;
    }
    .card-img-container {
        width: 100%;
        height: 200px;
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .card-img-container img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .card {
        height: 100%;
        width: 100%; 
        max-width: 300px;
    }

    .card-body {
        display: flex;
        flex-direction: column;
    }

    .card-text {
        flex-grow: 1;
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
    }
</style>

<div class="miniMenu">
    <p>Accueil - Nos catégories - {{ category.name }}</p>
</div>
<h1>{{ category.name }} <span class="badge text-bg-secondary">{{ category.itemCount }}</span></h1>

<div class="container">
    <div class="row">
        {% for item in category.items %}
        <div class="col-md-3 mb-4">
            <div class="card h-100">
                <div class="card-img-container">
                    <img src="{{ asset('/uploads/') ~ item.image }}" class="card-img-top" alt="{{ item.name }}">
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ item.name }}</h5>
                    <p class="card-text flex-grow-1">{{ item.description|raw }}</p>
                    <a href="{{ path('app_items_information', {id: item.id}) }}" class="btn btn-primary mt-auto">Voir plus</a>
                </div>
            </div>
        </div>
        {% else %}
<div class="alert alert-danger" role="alert">
  Aucun objet dans la catégorie {{ category.name }}
</div>
        {% endfor %}
    </div>
</div>
{% endblock %}